name: Flipper Zero app build

on:
  push:
    paths:
      - "flipperzero_app/**"
      - ".github/workflows/flipper-build.yml"
  pull_request:
    paths:
      - "flipperzero_app/**"
      - ".github/workflows/flipper-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ufbt
        run: pip install --upgrade ufbt

      - name: Build .fap
        working-directory: flipperzero_app
        run: ufbt
